replicaCount: 2

app:
  host: "logity-application"
  name: "LOGITY"
  apiPort: 8080
  externalPort: 80

auth:
  passwordHashCost: 7
  secretAccessKey: "secret_key"
  secretRefreshKey: "secret_key"
  accessTokenTTLInSec: 350
  refreshTokenTTLInSec: 3600

database:
  dsn: "postgresql://host.minikube.internal:6432/logity_auth?user=postgres&password=postgres&sslmode=disable"
  maxIdleConn: 3
  maxLifeTimeConn: 3

neo4j:
  host: "neo4j://host.minikube.internal:7687"
  boltHost: "jdbc:neo4j:bolt://host.minikube.internal:7687"
  database: "logity"
  username: "logity"
  password: "logitylogity"


centrifugo:
  apiHost: "http://centrifugo.default.svc.cluster.local:9000/api"
  clientHost: "ws://centrifugo.default.svc.cluster.local:8000/connection/websocket"
  apiKey: "NdnY4YDJ"
  secretKey: "4QH6JDhy"
  tokenTTLInSec: 3600

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 500Mi

liquibase:
  image: "liquibase/liquibase:latest"
  imageNeo4jLiquibase: "tobiskadocker/liquibase-neo4j:latest"
  pullPolicy: "Always"
  changelogLocationPostgres: "/liquibase/postgres"
  changelogLocationNeo4j: "/liquibase/neo4j"
  liquibaseChangelogLocation: "/liquibase/changelog"

image:
  repository: "tobiskadocker/logity"
  pullPolicy: "Always"
  tag: "latest"