linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - nakedret
    - gocyclo
    - unused
    - ineffassign
    - bodyclose
    - errname
    - gosimple
    - goconst
    - prealloc
    - reassign

linters-settings:
  gomnd:
    ignored-functions:
      - os.Chmod
      - os.Mkdir
      - os.MkdirAll
      - os.OpenFile
      - os.WriteFile
      - prometheus.ExponentialBuckets
      - prometheus.ExponentialBucketsRange
      - prometheus.LinearBuckets


run:
  go: '1.19'
  concurrency: 4
  timeout: 5m
  tests: false
  skip-dirs:
    - scripts
    - charts
    - cmd

issues:
   new-from-rev: HEAD~2

severity:
  default-severity: error
  rules:
    - linters:
        - errname
        - errcheck
        - prealloc
        - gocognit
        - gocyclo
        - gosimple
      severity: warn