version: '3'

services:
  logity:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - dev.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: logity_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  liquibase:
    image: liquibase/liquibase:4.15
    depends_on:
      - db
    volumes:
      - ./migration/postgres:/liquibase/changelog
    command: [
      "sh",
      "-c",
      "liquibase update --url=\"jdbc:postgresql://db:5432/logity_auth?user=postgres&password=postgres&sslmode=disable\" --changelog-file=\"changelog/changelog.xml\""
    ]

  neo4j:
    image: neo4j:5
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j:/var/lib/neo4j
    environment:
      # Raise memory limits
      - NEO4J_server.memory.pagecache.size=1G
      - NEO4J_server.memory.heap.initial.size=1G
      - NEO4J_server.memory.heap.max.size=1G

  liquibase-neo4j:
    image: liquibase/liquibase:4.15

    depends_on:
      - db
    volumes:
      - ./ext/neo4j:/liquibase/classpath
      - ./migration/neo4j:/liquibase/changelog
    command: [
      "sh",
      "-c",
      "liquibase update --url \"jdbc:neo4j:bolt//neo4j:5432\" --username neo4j --password sparta-ballad-domain-mars-miranda-5813 --changeLogFile \"changelog/changelog.xml\""
    ]

volumes:
  dbdata:
    driver: local
  neo4j:
    driver: local
