version: '3'

services:
  logity:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - dev.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: logity_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  liquibase:
    image: liquibase/liquibase:4.15
    depends_on:
      - db
    volumes:
      - ./migration/liquibase:/liquibase/changelog
    command: [
      "sh",
      "-c",
      "liquibase update --url=\"jdbc:postgresql://db:5432/logity_auth?user=postgres&password=postgres&sslmode=disable\" --changelog-file=\"changelog/changelog.xml\""
    ]

volumes:
  dbdata:
    driver: local
