version: '3'

services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v4
    volumes:
      - ./exports/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "8123:8000"
  logity:
    container_name: logity
    build:
      context: .
      dockerfile: build/app/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - dev.env
    depends_on:
      - postgres
      - neo4j

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - ./exports/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: logity_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  liquibase-postgres:
    container_name: liquibase-postgres
    image: liquibase/liquibase:4.15
    depends_on:
      - postgres
    volumes:
      - ./migration/postgres:/liquibase/changelog
    command: [
      "sh",
      "-c",
      "sleep 1 && liquibase update --url=\"jdbc:postgresql://postgres:5432/logity_auth?user=postgres&password=postgres&sslmode=disable\" --changelog-file=\"changelog/changelog.xml\""
    ]

  neo4j:
    container_name: neo4j
    image: neo4j:5.8.0-enterprise
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./exports/neo4j/data:/data
      - ./exports/neo4j/logs:/logs
      - ./exports/neo4j/plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_AUTH=neo4j/testifyt
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server.memory.pagecache.size=1G
      - NEO4J_server.memory.heap.initial.size=1G
      - NEO4J_server.memory.heap.max.size=1G

  liquibase-neo4j:
    container_name: liquibase-neo4j
    image: liquibase/liquibase:latest
    depends_on:
      - neo4j
    volumes:
      - ./exports/liquibase:/liquibase/lib
      - ./migration/neo4j:/liquibase/changelog
    command: [
      "sh",
      "-c",
      "liquibase update --url \"jdbc:neo4j:bolt://neo4j:7687?database=logity\" --username logity --password logitylogity --changeLogFile \"changelog/changelog.xml\""
    ]

volumes:
  dbdata:
    driver: local
  neo4j:
    driver: local
