version: '3'

services:
  logity:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - dev.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: logity_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  liquibase:
    image: liquibase/liquibase:4.15
    depends_on:
      - db
    volumes:
      - ./migration/liquibase:/liquibase/changelog
    command: [
      "sh",
      "-c",
      "liquibase update --url=\"jdbc:postgresql://db:5432/logity_auth?user=postgres&password=postgres&sslmode=disable\" --changelog-file=\"changelog/changelog.xml\""
    ]

  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j:/var/lib/neo4j
    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_security_ldap_authorization_system__username=neo4j
      - NEO4J_dbms_security_ldap_authorization_system__password=neo4j

volumes:
  dbdata:
    driver: local
  neo4j:
    driver: local
