---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-liquibase-postgres"
  labels:
    name: "{{ .Release.Name }}-{{ .Chart.Name }}-liquibase-postgres"
data:
  # Liquibase changelog
    {{- range $path, $_ :=  .Files.Glob  "files/liquibase/neo4j/**" }}
    {{- base $path | nindent 2 }}: |-
    {{- $.Files.Get $path | nindent 4 }}
    {{ end }}