apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-ingress"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}-ingress"

spec:
  rules:
    - host: app.example
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ .Release.Name }}-{{ .Chart.Name }}"
              port:
                number: {{ .Values.app.apiPort }}
