---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
data:
  POSTGRES_DSN: {{ .Values.database.dsn | b64enc | quote }}
  JDBC_URL: {{ printf "jdbc:%s" .Values.database.dsn | b64enc | replace "postgres:" "postgresql:" | quote }}
  BOLT_URL: {{ printf "jdbc:bolt:%s" .Values.neo4j.host | b64enc | quote }}
  SECRET_ACCESS_KEY: {{ .Values.auth.secretAccessKey | b64enc | quote }}
  SECRET_REFRESH_KEY: {{ .Values.auth.secretRefreshKey | b64enc | quote }}
  CENTRIFUGO_SECRET_KEY: {{ .Values.centrifugo.secretKey | b64enc | quote }}
  CENTRIFUGO_API_KEY: {{ .Values.centrifugo.apiKey | b64enc | quote }}
  NEO4J_USERNAME: {{ .Values.neo4j.username | b64enc | quote }}
  NEO4J_PASSWORD: {{ .Values.neo4j.password | b64enc | quote }}

...