---
apiVersion: v1
kind: Secret
type: Opaque
data:
  POSTGRES_DSN: {{ .Values.database.dsn }}

  SECRET_ACCESS_KEY: {{ .Values.auth.secretAccessKey | b64enc }}
  SECRET_REFRESH_KEY: {{ .Values.auth.secretRefreshKey | b64enc }}

  CENTRIFUGO_SECRET_KEY: {{ .Values.centrifugo.secretKey | b64enc }}
  CENTRIFUGO_API_KEY: {{ .Values.centrifugo.apiKey | b64enc }}

  NEO4J_USERNAME: {{ .Values.neo4j.username | b64enc }}
  NEO4J_PASSWORD: {{ .Values.neo4j.password | b64enc }}

...