apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name}}"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name}}"

spec:
  type: ClusterIP
  selector:
    name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
    - name: http
      port: {{ .Values.app.apiPort }}
      protocol: TCP
      targetPort: {{ .Values.app.apiPort }}


